name: remote ssh command
on: 
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/project:latest          
    - 
      name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git pull origin main -
          docker rmi ${{ secrets.DOCKER_USER }}/project
          docker pull ${{ secrets.DOCKER_USER }}/project-
          docker stop project 
          docker rm project
          docker run -d -p 8000:8000 -e SERVER_PORT=${{ secrets.SERVER_PORT }} -e DBUSER=${{ secrets.DBUSER }} -e DBPASS=${{ secrets.DBPASS }} -e DBHOST=${{ secrets.DBHOST }} -e DBPORT=${{ secrets.DBPORT }} -e DBNAME=${{ secrets.DBNAME }} -e AWS_BUCKET_NAME=${{secrets.AWS_BUCKET_NAME}} -e AWS_REGION=${{secrets.AWS_REGION}} -e ACCESS_KEY_IAM=${{secrets.ACCESS_KEY_IAM}} -e SECRET_KEY_IAM=${{secrets.SECRET_KEY_IAM}} --name project ${{ secrets.DOCKER_USER }}/project:latest 
